import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Link from "next/link";
import { Camera, Home, LayoutGrid, Search, User } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}
      >
        <Theme>
          {children}
          <div className="fixed bottom-0 left-0 right-0">
            <div className="flex *:flex *:items-center">
              <div className="pl-2 bg-white rounded-t-xl w-full relative z-10 *:size-12 *:flex *:items-center *:justify-center justify-around">
                <Link href="/" className="">
                  <Home/>
                </Link>
                <Link href="/search" className="">
                  <Search/>
                </Link>
              </div>
              <div className="size-14 relative -top-4 justify-center w-[125px]">
                <div className="absolute bg-blue-500 bg-clip-text border-white border-t-transparent border-l-transparent border-[50px] rounded-full rotate-45">
                  <div className="border-4 size-15 border-transparent">
                    <Link href="/create" className="-rotate-45 bg-gradient-to-tr from-ig-orange to-ig-red size-12 flex items-center justify-center text-white rounded-full ">
                      <Camera/>
                    </Link>
                  </div>
                </div>
              </div>
              <div className="pr-2 bg-white rounded-t-xl w-full relative z-10 *:size-12 *:flex *:items-center *:justify-center justify-around">
                <Link href="/browse" className="">
                  <LayoutGrid/>
                </Link>
                <Link href="/profile" className="text-ig-red ">
                  <User/>
                </Link>
              </div>
            </div>
          </div>
        </Theme>
      </body>
    </html>
  );
}